version: '3.8'

services:
  app:
    build: .
    ports:
      - "9000:9000"
      - "9999:9999"
    environment:
      - NODE_ENV=production
      - GCP_DEPLOYMENT=true
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - X_API_BEARER_TOKEN=${X_API_BEARER_TOKEN}
      - GROK_API_KEY=${GROK_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
    volumes:
      - ./python-scraper/output:/app/python-scraper/output
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
